### PR TITLE
feat: add config option to only lint PR title

### LINKED ISSUE #29: Bot is approving incorrect PR title
Not sure if I'm missing the purpose of this bot, but I was under the impression it is essentially linting PR titles to match conventional-commit format.

This PR has an incorrect title yet the semantic-pull-request check has passed.
https://github.com/guyfedwards/emojo/pull/18

### PR DESCRIPTION
**Pull request by guyfedwards**
What are your thoughts about having the config file as it seems that the config file will now be required even if the user wants the default settings? I am confirming this here https://github.com/probot/probot-config/issues/23

This is useful when merging by squashing as the PR title is the default
commit message for the squash commit.

Closes #29

-----
[View rendered README.md](https://github.com/guyfedwards/semantic-pull-requests/blob/only-title-linting-option/README.md)

### CODE REVIEW

**Comment by zeke** [comment]
Thanks for submitting this, @guyfedwards.

Since this PR is introducing configuration to the project, I think it would be useful to consider other ways people might want to configure the bot so we have a naming scheme that is flexible from the start.

A few configurations come to mind:

- title or at least one commit is semantic (current behavior)
- all commits are semantic
- title is semantic
- title and all commits are semantic

Also, let me play devil's advocate for a moment and suggest that maybe we can make the bot accomodate all use cases without requiring configuration. In #29, I suggested:

> One approach would be to make the bot check what types of merging are allowed on the repo (rebase/squash/merge), and if squash is the only allowed merge type, then the requirements would change and the PR title would then have to be semantic.

@guyfedwards would this approach work you? If not, why not?

Just want to clarify: I don't intend to block progress here. Happy to merge this and ship it, but want to consider our options carefully first.

**Comment by guyfedwards** [comment]
Agreed about the improved naming scheme, are you suggesting having them as string options for a `mergeType: 'title_commit'` style property in the config? Or a set of various boolean flags like: 
```
semanticCommits: boolean
semancticTitle: boolean
```
? 

I'm not sure how viable the inferred settings would be but my main reasoning against that approach would be that it moves the configuration out of the code and into Github settings. 
Now every time I want to use my setup in a new repo, I must change Github settings as well as install the bot, instead of just copying the `.github/semantic.yml` file which is both version controlled and it would seem shareable/extendable.

I am also keen to see the outcome of https://github.com/probot/probot-config/issues/23 as I don't like the idea of forcing users to include a config file if they wish to use the default settings as this seems unnecessary, but I'm sure this is just my misunderstanding or missing some config.

**Comment by zeke** [comment]
What about something like this:

```yml
validate: title
validate: allCommits
validate: anyCommit
validate: titleOrAnyCommit
validate: titleAndAllCommits
```

or

```yml
validate:
  title: true
  commits: true # or `false` or `atLeastOne`
```

**Comment by zeke** [comment]
The second format above is simpler, but doesn't account for the current behavior of "title OR any commit"...

**Comment by guyfedwards** [comment]
hmm yea that's a tough one. The second is much cleaner but I think the first is more flexible and ends up being clearer than having `boolean`/`string` options mixed in the second.

Just a thought we could allow `boolean` or more granular options for commits, creates more of a settings matrix: 
```
validate:
  title: true 
  commits: true # enable all commits
atLeastOne: false # title and commits are required
```

```
validate:
  title: true
  commits: 
    enabled: true
    atLeastOne: true # atLeastOne commit required
```

That has the potential to get a little out of hand going forward but also is quite flexible ¯\\_(ツ)_/¯

I am happy to go number one otherwise :+1:

**Comment by zeke** [comment]
@guyfedwards rather than continuing to pontificate, I decided to go ahead and ship this. Let's see how it feels and we can iterate if needed.

**Comment by mrchief** [comment]
@zeke is there way to support this currently?

```
validate:
  title: true
  commits: 
    enabled: true
    atLeastOne: true # atLeastOne commit required
```

GH PRs with non semantic single commits cause issues otherwise.

**Pull request merged**
